import { double, int, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", { id:int("id").autoincrement().primaryKey(), openId:varchar("openId",{length:128}).notNull().unique(), name:text("name"), email:varchar("email",{length:320}), loginMethod:varchar("loginMethod",{length:64}), username:varchar("username",{length:80}).unique(), passwordHash:text("passwordHash"), jobTitle:varchar("jobTitle",{length:120}), role:mysqlEnum("role",["user","admin"]).default("user").notNull(), permissionsJson:text("permissionsJson"), createdAt:timestamp("createdAt").defaultNow().notNull(), updatedAt:timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn:timestamp("lastSignedIn").defaultNow().notNull() });
export const customers = mysqlTable("customers", { id:int("id").autoincrement().primaryKey(), name:varchar("name",{length:160}).notNull(), phone:varchar("phone",{length:40}).notNull(), business:varchar("business",{length:180}).default("").notNull(), city:varchar("city",{length:120}).default("").notNull(), address:text("address").notNull(), lat:double("lat"), lng:double("lng"), status:mysqlEnum("status",["ثابت","غیر ثابت","نیاز به پیگیری","در حال پیگیری"]).default("غیر ثابت").notNull(), note:text("note"), createdAt:timestamp("createdAt").defaultNow().notNull(), updatedAt:timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const orders = mysqlTable("orders", { id:int("id").autoincrement().primaryKey(), customerId:int("customerId").notNull(), jalaliDate:varchar("jalaliDate",{length:32}).notNull(), address:text("address").notNull(), lat:double("lat"), lng:double("lng"), itemsJson:text("itemsJson").notNull(), total:int("total").default(0).notNull(), status:mysqlEnum("status",["pending","delivered"]).default("pending").notNull(), notes:text("notes"), deliveryMethod:varchar("deliveryMethod",{length:80}), deliveryCost:int("deliveryCost"), deliveryAt:timestamp("deliveryAt"), deliveryNote:text("deliveryNote"), createdAt:timestamp("createdAt").defaultNow().notNull() });
export const orderHistory = mysqlTable("orderHistory", { id:int("id").autoincrement().primaryKey(), orderId:int("orderId").notNull(), action:varchar("action",{length:80}).notNull(), details:text("details").notNull(), createdAt:timestamp("createdAt").defaultNow().notNull() });
export const activities = mysqlTable("activities", { id:int("id").autoincrement().primaryKey(), text:varchar("text",{length:255}).notNull(), createdAt:timestamp("createdAt").defaultNow().notNull() });
export const activityDismissals = mysqlTable("activityDismissals", { id:int("id").autoincrement().primaryKey(), activityId:int("activityId").notNull(), userOpenId:varchar("userOpenId",{length:128}).notNull(), createdAt:timestamp("createdAt").defaultNow().notNull() });
export const appSettings = mysqlTable("appSettings", { key:varchar("key",{length:80}).primaryKey(), value:text("value").notNull(), updatedAt:timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const restoreHistory = mysqlTable("restoreHistory", { id:int("id").autoincrement().primaryKey(), userOpenId:varchar("userOpenId",{length:128}), userName:varchar("userName",{length:180}).notNull(), backupVersion:int("backupVersion").default(1).notNull(), recordCount:int("recordCount").default(0).notNull(), createdAt:timestamp("createdAt").defaultNow().notNull() });
export const inventoryItems = mysqlTable("inventoryItems", { id:int("id").autoincrement().primaryKey(), kind:mysqlEnum("kind",["garment","material"]).notNull(), dataJson:text("dataJson").notNull(), createdAt:timestamp("createdAt").defaultNow().notNull(), updatedAt:timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const inventoryMovements = mysqlTable("inventoryMovements", { id:int("id").autoincrement().primaryKey(), inventoryItemId:int("inventoryItemId").notNull(), branchPath:varchar("branchPath",{length:255}).default("کل موجودی").notNull(), direction:mysqlEnum("direction",["in","out","adjustment"]).notNull(), quantity:int("quantity").notNull(), previousQuantity:int("previousQuantity"), unit:varchar("unit",{length:40}).default("عدد").notNull(), note:text("note"), changeReason:text("changeReason"), isDeleted:int("isDeleted").default(0).notNull(), createdAt:timestamp("createdAt").defaultNow().notNull(), updatedAt:timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export type User=typeof users.$inferSelect; export type InsertUser=typeof users.$inferInsert; export type Customer=typeof customers.$inferSelect; export type Order=typeof orders.$inferSelect; export type OrderHistory=typeof orderHistory.$inferSelect; export type Activity=typeof activities.$inferSelect; export type ActivityDismissal=typeof activityDismissals.$inferSelect; export type AppSetting=typeof appSettings.$inferSelect; export type RestoreHistory=typeof restoreHistory.$inferSelect; export type InventoryItem=typeof inventoryItems.$inferSelect; export type InventoryMovement=typeof inventoryMovements.$inferSelect;
