import { Check, ChevronDown, Eye, EyeOff, KeyRound, ShieldCheck, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
const sections=["فروش و مشتری‌ها","ثبت سفارش","تحویل محصول","انبار","گزارش‌ها","مدیریت کاربران"] as const;
type Permission="view"|"edit"|"none";
type User={id:number;name:string|null;email:string|null;role:"user"|"admin";permissionsJson:string|null};
const modeLabel={view:"فقط مشاهده",edit:"دسترسی کامل",none:"بدون دسترسی"};
const defaultPermissions=(role:"user"|"admin")=>Object.fromEntries(sections.map(section=>[section,role==="admin"?"edit":"none"])) as Record<string,Permission>;
const parsePermissions=(user:User)=>{try{return {...defaultPermissions(user.role),...(user.permissionsJson?JSON.parse(user.permissionsJson):{})} as Record<string,Permission>}catch{return defaultPermissions(user.role)}};
export default function Access(){
 const usersQuery=trpc.users.list.useQuery(undefined,{refetchInterval:3000,refetchIntervalInBackground:true}); const updateUser=trpc.users.update.useMutation(); const utils=trpc.useUtils();
 const users=(usersQuery.data||[]) as User[]; const [selectedId,setSelectedId]=useState(0); const [notice,setNotice]=useState("");
 useEffect(()=>{if(users.length&&!users.some(user=>user.id===selectedId))setSelectedId(users[0].id)},[users,selectedId]);
 const selected=users.find(user=>user.id===selectedId); const permissions=useMemo(()=>selected?parsePermissions(selected):{},[selected]);
 const setPermission=async(section:string,permission:Permission)=>{if(!selected)return;const next={...permissions,[section]:permission};await updateUser.mutateAsync({id:selected.id,data:{permissionsJson:JSON.stringify(next)}});await utils.users.list.invalidate();setNotice(`سطح «${section}» برای ${selected.name||selected.email||"کاربر"} ذخیره شد.`)};
 const setRole=async(role:"user"|"admin")=>{if(!selected)return;const next=role==="admin"?defaultPermissions("admin"):permissions;await updateUser.mutateAsync({id:selected.id,data:{role,permissionsJson:JSON.stringify(next)}});await utils.users.list.invalidate();setNotice("نقش و سطح دسترسی کاربر به‌روزرسانی شد.")};
 return <div className="access-page"><div className="page-heading"><div><span className="eyebrow">مدیریت سازمان و نقش‌ها</span><h1>دسترسی کاربران</h1><p>کاربران از دیتابیس خوانده می‌شوند و تغییرات دسترسی برای همه نشست‌ها ذخیره و به‌روزرسانی می‌شود.</p></div><button className="outline-button" onClick={()=>usersQuery.refetch()}><UsersRound size={16}/> به‌روزرسانی فهرست</button></div><div className="access-banner"><div className="access-banner-icon"><KeyRound size={22}/></div><div><strong>کاربر جدید پس از ورود نمایش داده می‌شود</strong><p>هر کاربری که با حساب سازمانی وارد شود در این فهرست قرار می‌گیرد؛ نیازی به داده نمونه نیست.</p></div><ShieldCheck size={25}/></div>{usersQuery.isLoading?<section className="data-card access-empty-card"><strong>در حال دریافت کاربران...</strong></section>:!users.length?<section className="data-card access-empty-card"><UsersRound size={30}/><h2>فهرست کاربران خالی است</h2><p>پس از ورود کاربر جدید، صفحه را باز کنید یا دکمه به‌روزرسانی را بزنید.</p></section>:<div className="access-grid"><section className="data-card user-list"><div className="table-head"><div><h3>کاربران مجموعه</h3><span>{users.length.toLocaleString("fa-IR")} کاربر فعال</span></div><UsersRound size={19}/></div>{users.map(user=><button type="button" className={`user-row ${selected?.id===user.id?"active":""}`} key={user.id} onClick={()=>setSelectedId(user.id)}><div className="customer-avatar">{(user.name||user.email||"ک").slice(0,1)}</div><div><strong>{user.name||"بدون نام"}</strong><span>{user.email||"ایمیل ثبت نشده"}</span></div><span className="role-badge">{user.role==="admin"?"مدیر سیستم":"کاربر"}</span><ChevronDown size={15}/></button>)}</section><section className="data-card access-editor">{selected&&<><div className="editor-head"><div><span className="eyebrow">ویرایش دسترسی</span><h2>{selected.name||"بدون نام"}</h2><p>{selected.email||"ایمیل ثبت نشده"}</p></div><ShieldCheck size={22}/></div><label className="role-field">نقش کاربر<select value={selected.role} onChange={event=>setRole(event.target.value as "user"|"admin")}><option value="user">کاربر عادی</option><option value="admin">مدیر سیستم</option></select></label><div className="permission-title"><strong>سطح دسترسی به بخش‌ها</strong><span>هر تغییر بلافاصله در دیتابیس ذخیره می‌شود.</span></div><div className="permission-grid permission-matrix">{sections.map(section=>{const permission=permissions[section]||"none";return <div className="permission-row" key={section}><div className="permission-name">{permission==="edit"?<Check size={15}/>:permission==="view"?<Eye size={15}/>:<EyeOff size={15}/>}<strong>{section}</strong></div><div className="permission-options">{(["view","edit","none"] as Permission[]).map(mode=><button type="button" key={mode} className={permission===mode?`permission-${mode}`:""} onClick={()=>setPermission(section,mode)}>{modeLabel[mode]}</button>)}</div></div>})}</div></>}</section></div>}{notice&&<div className="toast">{notice}</div>}</div>;
}
