import { ArrowRight, CheckCircle2, Clock3, Download, Edit3, FileText, MapPin, Package, Printer, Truck } from "lucide-react";
import { useLocation } from "wouter";
import { MapView } from "@/components/Map";
import { trpc } from "@/lib/trpc";
import { currencyLabel, formatCurrency, useCurrency } from "@/hooks/useCurrency";
import { useRefreshInterval } from "@/hooks/useRefreshInterval";

const money=(value:number)=>formatCurrency(value);
const formatDate=(value:Date|string|number|null|undefined,withTime=false)=>value?new Intl.DateTimeFormat("fa-IR-u-ca-persian",{year:"numeric",month:"long",day:"numeric",...(withTime?{hour:"2-digit",minute:"2-digit"}:{})}).format(new Date(value)):"ثبت نشده";
const actionLabels:Record<string,string>={created:"ثبت سفارش",updated:"ویرایش سفارش",delivered:"ثبت تحویل"};

export default function OrderDetails(){
  useCurrency();
  const [location,setLocation]=useLocation();
  const id=Number(location.match(/\/orders\/(\d+)/)?.[1]||0);
  const refreshInterval=useRefreshInterval();
  const detailQuery=trpc.crm.orderDetails.useQuery({id},{enabled:id>0,refetchInterval:refreshInterval,refetchIntervalInBackground:true});
  const detail=detailQuery.data;
  if(detailQuery.isLoading)return <div className="order-detail-page"><div className="detail-loading">در حال دریافت جزئیات سفارش...</div></div>;
  if(!detail)return <div className="order-detail-page"><div className="detail-empty"><Package size={30}/><h2>سفارش پیدا نشد</h2><p>این سفارش حذف شده یا شناسه آن معتبر نیست.</p><button className="primary-button" onClick={()=>setLocation("/orders")}>بازگشت به سفارش‌ها</button></div></div>;
  const {order,customer,history}=detail;
  let items:any[]=[];try{items=JSON.parse(order.itemsJson||"[]")}catch{items=[]}
  const printOrder=()=>{const previousTitle=document.title;document.title=`پیش‌فاکتور سفارش ${order.id}`;window.setTimeout(()=>{window.print();window.setTimeout(()=>{document.title=previousTitle},500)},50)};
  return <div dir="rtl" className="order-detail-page">
    <div className="detail-page-head"><button className="back-button" onClick={()=>setLocation("/orders")}><ArrowRight size={18}/> بازگشت به سفارش‌ها</button><div><span className="eyebrow">پرونده کامل سفارش</span><h1>سفارش #{order.id}</h1><p>تمام مشخصات خرید، تحویل و تاریخچه تغییرات در یک صفحه.</p></div><div className="detail-page-actions"><button className="outline-button" onClick={printOrder}><Printer size={17}/> چاپ مستقیم</button><button className="outline-button" onClick={printOrder}><Download size={17}/> دانلود PDF</button><button className="primary-button" onClick={()=>setLocation(`/orders/new?order=${order.id}`)}><Edit3 size={17}/> ویرایش سفارش</button></div></div>
    <div className="detail-status-strip"><span className={order.status==="delivered"?"status green":"status amber"}>{order.status==="delivered"?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} {order.status==="delivered"?"تحویل داده‌شده":"در انتظار تحویل"}</span><span><FileText size={15}/> تاریخ سفارش: {order.jalaliDate}</span><strong>{money(order.total)}</strong></div>
    <div className="order-detail-grid">
      <main>
        <section className="detail-panel"><div className="detail-panel-title"><div><span className="eyebrow">خریدار</span><h2>اطلاعات مشتری</h2></div><MapPin size={20}/></div><div className="customer-detail-grid"><div><span>نام مشتری</span><strong>{customer?.name||"—"}</strong></div><div><span>شماره تماس</span><strong>{customer?.phone||"—"}</strong></div><div><span>صنف / مجموعه</span><strong>{customer?.business||"—"}</strong></div><div><span>شهر</span><strong>{customer?.city||"—"}</strong></div><div className="span-two"><span>آدرس سفارش</span><strong>{order.address||customer?.address||"—"}</strong></div></div></section>
        <section className="detail-panel"><div className="detail-panel-title"><div><span className="eyebrow">فاکتور</span><h2>اقلام و جزئیات خرید</h2></div><Package size={20}/></div>{items.length?items.map((item,index)=>{const sizes=item.sizes||[];const qty=Number(item.qty||sizes.reduce((sum:number,row:any)=>sum+Number(row.qty||0),0));const itemTotal=qty*(Number(item.unit||0)+Number(item.frontPrice||0)+Number(item.backPrice||0)+Number(item.materialPrice||0));return <article className="detail-item" key={`${item.id||item.product||"item"}-${index}`}><div className="detail-item-head"><strong>{item.product||item.type||"محصول"}</strong><span>{qty.toLocaleString("fa-IR")} عدد</span></div><div className="detail-item-meta"><span>جنس: {item.fabric||"—"}</span><span>رنگ: {item.color||"—"}</span><span>دکمه: {item.button||"—"}</span><span>زیپ: {item.zipper||"—"}</span><span>جیب: {item.pocket||"—"}</span><span>چاپ جلو: {item.front||"—"}</span><span>چاپ پشت: {item.back||"—"}</span></div>{sizes.length>0&&<div className="detail-size-list">{sizes.map((row:any,sizeIndex:number)=><span key={`${row.size||"size"}-${sizeIndex}`}>{row.size||"بدون سایز"}: <b>{Number(row.qty||0).toLocaleString("fa-IR")}</b></span>)}</div>}<div className="detail-item-total">مبلغ قلم: <strong>{money(itemTotal)}</strong></div></article>}) : <div className="detail-empty-inline">جزئیات اقلام ثبت نشده است.</div>}<div className="detail-total-row"><span>جمع کل سفارش</span><strong>{money(order.total)}</strong></div></section>
        {order.status==="delivered"&&<section className="detail-panel delivery-detail-panel"><div className="detail-panel-title"><div><span className="eyebrow">تحویل</span><h2>اطلاعات ارسال و دریافت</h2></div><Truck size={20}/></div><div className="customer-detail-grid"><div><span>روش ارسال</span><strong>{order.deliveryMethod||"ثبت نشده"}</strong></div><div><span>هزینه باربری / ارسال</span><strong>{money(order.deliveryCost||0)}</strong></div><div><span>تاریخ و زمان تحویل</span><strong>{formatDate(order.deliveryAt,true)}</strong></div><div className="span-two"><span>توضیحات تحویل</span><strong>{order.deliveryNote||"توضیحی ثبت نشده است."}</strong></div></div></section>}
        <section className="detail-panel"><div className="detail-panel-title"><div><span className="eyebrow">Timeline</span><h2>تاریخچه تغییرات سفارش</h2></div><Clock3 size={20}/></div><div className="order-timeline">{history.length?history.map((event:any)=><div className="timeline-event" key={event.id}><i/><div><strong>{actionLabels[event.action]||event.action}</strong><time>{formatDate(event.createdAt,true)}</time><p>{event.action==="created"?"سفارش در سیستم ثبت شد.":event.action==="delivered"?"وضعیت سفارش به تحویل داده‌شده تغییر کرد و اطلاعات ارسال ذخیره شد.":"اطلاعات سفارش یا موقعیت مشتری ویرایش شد."}</p><details><summary>مشاهده داده تغییر</summary><pre>{event.details}</pre></details></div></div>) : <div className="detail-empty-inline">هنوز تغییری در تاریخچه ثبت نشده است.</div>}</div></section>
      </main>
      <aside>
        <section className="detail-panel detail-map-panel"><div className="detail-panel-title"><div><span className="eyebrow">موقعیت</span><h2>لوکیشن سفارش</h2></div><MapPin size={20}/></div><MapView className="detail-location-map" initialCenter={{lat:Number(order.lat||customer?.lat||35.7219),lng:Number(order.lng||customer?.lng||51.3347)}} initialZoom={14} onMapReady={map=>{map.setOptions({clickableIcons:false,gestureHandling:"cooperative"});try{new window.google.maps.marker.AdvancedMarkerElement({map,position:{lat:Number(order.lat||customer?.lat||35.7219),lng:Number(order.lng||customer?.lng||51.3347)},title:order.address||"لوکیشن سفارش"})}catch{}}}/><p className="map-address"><MapPin size={15}/>{order.address||customer?.address||"آدرس ثبت نشده"}</p></section>
        <section className="detail-panel quick-facts"><div className="detail-panel-title"><div><span className="eyebrow">خلاصه</span><h2>اطلاعات ثبت</h2></div></div><div><span>شناسه مشتری</span><strong>{order.customerId.toLocaleString("fa-IR")}</strong></div><div><span>تاریخ ایجاد رکورد</span><strong>{formatDate(order.createdAt,true)}</strong></div><div><span>یادداشت سفارش</span><strong>{order.notes||"یادداشتی ثبت نشده است."}</strong></div></section>
      </aside>
    </div>
  </div>;
}
