import { useMemo, useState } from "react";
import { ArrowLeft, Building2, CheckCircle2, ChevronDown, Clock3, Edit3, Filter, History, MapPin, MoreHorizontal, Phone, Plus, Search, ShieldCheck, Star, UserRound, UserRoundCheck, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

export type CustomerStatus = "ثابت" | "غیر ثابت" | "نیاز به پیگیری" | "در حال پیگیری";
type Customer = { id:string; name:string; phone:string; business:string; city:string; address:string; status:CustomerStatus; orders:number; total:number; joined:number; lastOrder?:number; note:string; location:{lat:number;lng:number;label:string}; };

const initialCustomers: Customer[] = [
 {id:"CUS-1001",name:"مریم محمدی",phone:"۰۹۱۲ ۶۸۴ ۱۰۴۸",business:"کافه آتریوم",city:"تهران",address:"ونک، خیابان ملاصدرا، کوچه نهم، پلاک ۲۴",status:"ثابت",orders:4,total:72800000,joined:new Date(2025,5,12).getTime(),lastOrder:new Date(2026,8,8).getTime(),note:"مشتری قدیمی؛ ترجیح ارسال فوری.",location:{lat:35.7549,lng:51.4096,label:"ونک، ملاصدرا"}},
 {id:"CUS-1002",name:"علی شریفی",phone:"۰۹۱۳ ۳۲۱ ۸۰۲۱",business:"رستوران ترنج",city:"اصفهان",address:"خیابان چهارباغ بالا، مجتمع سپاهان",status:"در حال پیگیری",orders:2,total:38300000,joined:new Date(2026,4,18).getTime(),lastOrder:new Date(2026,8,7).getTime(),note:"پیگیری نمونه رنگ جدید برای سفارش زمستان.",location:{lat:32.6333,lng:51.6422,label:"چهارباغ بالا، اصفهان"}},
 {id:"CUS-1003",name:"لیلا اکبری",phone:"۰۹۱۵ ۴۱۲ ۶۹۰۲",business:"کلینیک آرمان",city:"مشهد",address:"بلوار سجاد، بین حامد و بهارستان",status:"ثابت",orders:6,total:124400000,joined:new Date(2024,10,2).getTime(),lastOrder:new Date(2026,8,5).getTime(),note:"خرید فصلی؛ مسئول خرید خانم اکبری.",location:{lat:36.3133,lng:59.5269,label:"بلوار سجاد، مشهد"}},
 {id:"CUS-1004",name:"سارا رستمی",phone:"۰۹۱۲ ۷۶۸ ۱۴۹۰",business:"آموزشگاه زبان دایان",city:"کرج",address:"عظیمیه، بلوار شریعتی، برج آرین",status:"غیر ثابت",orders:1,total:11800000,joined:new Date(2026,7,28).getTime(),note:"اولین خرید ثبت شد؛ رضایت‌سنجی انجام شود.",location:{lat:35.8401,lng:50.9391,label:"عظیمیه، کرج"}},
 {id:"CUS-1005",name:"حسین مرادی",phone:"۰۹۱۱ ۲۴۳ ۸۴۲۰",business:"فروشگاه پوشاک آریا",city:"رشت",address:"گلسار، خیابان ۱۰۵، پلاک ۶",status:"نیاز به پیگیری",orders:0,total:0,joined:new Date(2026,8,1).getTime(),note:"پیش‌فاکتور ارسال شده؛ منتظر پاسخ.",location:{lat:37.2808,lng:49.5832,label:"گلسار، رشت"}},
];
const money=(v:number)=>`${v.toLocaleString("fa-IR")} تومان`;
const date=(v:number)=>new Intl.DateTimeFormat("fa-IR-u-ca-persian",{year:"numeric",month:"short",day:"numeric"}).format(new Date(v));
const statusClass=(s:CustomerStatus)=>s==="ثابت"?"green":s==="غیر ثابت"?"gray":s==="نیاز به پیگیری"?"red":"amber";

export default function Sales(){
 const [,setLocation]=useLocation(); const [customers,setCustomers]=useState<Customer[]>(()=>{try{return JSON.parse(localStorage.getItem("taraz-customers")||"")||initialCustomers}catch{return initialCustomers}}); const [segment,setSegment]=useState<"همه"|CustomerStatus>("همه"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState(customers[0]); const [notice,setNotice]=useState("");
 const filtered=useMemo(()=>customers.filter(c=>(segment==="همه"||c.status===segment)&&`${c.name} ${c.city} ${c.business} ${c.phone} ${c.status}`.includes(query.trim())),[customers,segment,query]);
 const promote=(id:string)=>{setCustomers(data=>{const next=data.map(c=>c.id===id?{...c,status:"ثابت" as CustomerStatus}:c);localStorage.setItem("taraz-customers",JSON.stringify(next));return next});setNotice("مشتری به فهرست مشتریان ثابت اضافه شد.")};
 return <div className="sales-page">
  <div className="page-heading"><div><span className="eyebrow">فروش · ارتباط با مشتری</span><h1>مشتری‌ها</h1><p>تمام ارتباط‌ها، سوابق خرید و وضعیت پیگیری مشتریان تولیدی پوشاک سپید.</p></div><button className="primary-button" onClick={()=>setLocation("/orders/new")}><Plus size={18}/> ثبت سفارش برای مشتری</button></div>
  <div className="sales-kpis"><div><UsersRound size={19}/><span>همه مشتری‌ها</span><strong>{customers.length.toLocaleString("fa-IR")}</strong></div><div><UserRoundCheck size={19}/><span>مشتری ثابت</span><strong>{customers.filter(c=>c.status==="ثابت").length.toLocaleString("fa-IR")}</strong></div><div><Clock3 size={19}/><span>نیازمند پیگیری</span><strong>{customers.filter(c=>c.status==="نیاز به پیگیری"||c.status==="در حال پیگیری").length.toLocaleString("fa-IR")}</strong></div><div><Building2 size={19}/><span>فروش ثبت‌شده</span><strong>{money(customers.reduce((s,c)=>s+c.total,0))}</strong></div></div>
  <div className="segment-tabs">{(["همه","ثابت","غیر ثابت","نیاز به پیگیری","در حال پیگیری"] as const).map(item=><button key={item} className={segment===item?"selected":""} onClick={()=>setSegment(item)}>{item}<b>{(item==="همه"?customers:customers.filter(c=>c.status===item)).length.toLocaleString("fa-IR")}</b></button>)}</div>
  <div className="toolbar"><div className="search-field"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجو بر اساس نام، شهر، صنف، شماره..."/><kbd>⌘ K</kbd></div><div className="toolbar-actions"><button className="filter-button"><Filter size={17}/> شهر <ChevronDown size={15}/></button><button className="filter-button"><Filter size={17}/> وضعیت مشتری <ChevronDown size={15}/></button></div></div>
  <div className="sales-layout"><section className="data-card customer-table"><div className="table-head"><div><h3>فهرست مشتری‌ها</h3><span>{filtered.length.toLocaleString("fa-IR")} مورد نمایش داده می‌شود</span></div><button className="filter-button"><MoreHorizontal size={16}/> عملیات</button></div>{filtered.map(c=><button className={`customer-row ${selected?.id===c.id?"active":""}`} key={c.id} onClick={()=>setSelected(c)}><div className="customer-avatar">{c.name.slice(0,1)}</div><div className="customer-main"><strong>{c.name}</strong><span>{c.business} · {c.city}</span></div><div className="customer-orders"><strong>{c.orders.toLocaleString("fa-IR")} خرید</strong><span>{c.lastOrder?date(c.lastOrder):"هنوز خریدی ثبت نشده"}</span></div><span className={`status-pill ${statusClass(c.status)}`}>{c.status}</span><ArrowLeft size={16}/></button>)}{!filtered.length&&<div className="empty-state"><UsersRound size={26}/><strong>مشتری‌ای با این مشخصات پیدا نشد.</strong></div>}</section>
  {selected&&<aside className="customer-profile"><div className="profile-head"><div className="profile-avatar">{selected.name.slice(0,1)}</div><div><span className={`status-pill ${statusClass(selected.status)}`}>{selected.status}</span><h2>{selected.name}</h2><p>{selected.business}</p></div><button className="icon-button"><Edit3 size={17}/></button></div><div className="profile-actions"><button className="outline-button"><Phone size={15}/> تماس</button><button className="primary-button" onClick={()=>setLocation(`/orders/new?customer=${selected.id}`)}><Plus size={15}/> ثبت خرید جدید</button></div><div className="profile-info"><div><Phone size={15}/><span>{selected.phone}</span></div><div><MapPin size={15}/><span>{selected.address}</span></div><div><ShieldCheck size={15}/><span>عضویت از {date(selected.joined)}</span></div></div><div className="profile-note"><strong>یادداشت فروش</strong><p>{selected.note}</p></div><div className="purchase-history"><div className="section-title"><div><History size={16}/><strong>تاریخچه خرید</strong></div><span>{selected.orders.toLocaleString("fa-IR")} خرید</span></div>{selected.orders? ["کاپشن کجراه سرمه‌ای","پیراهن فرم کرم","مانتو فرم طوسی"].slice(0,Math.min(selected.orders,3)).map((p,i)=><div className="purchase-item" key={p}><div><span>خرید {(i+1).toLocaleString("fa-IR")}</span><strong>{p}</strong></div><div><b>{money(19600000-i*3100000)}</b><small>{date(new Date(2026,8,8-i*18).getTime())}</small></div></div>):<div className="empty-mini">هنوز فاکتور خریدی ثبت نشده است.</div>}</div>{selected.status!=="ثابت"&&<button className="promote-button" onClick={()=>promote(selected.id)}><Star size={16}/> افزودن به مشتری‌های ثابت</button>}</aside>}
  </div>{notice&&<div className="toast"><CheckCircle2 size={18}/>{notice}</div>}
 </div>;
}
