import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { activities, customers, InsertUser, inventoryItems, inventoryMovements, orderHistory, orders, users } from "../drizzle/schema";
import { ENV } from './_core/env';

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb(){if(!_db&&process.env.DATABASE_URL){try{_db=drizzle(process.env.DATABASE_URL)}catch(error){console.warn("[Database] Failed to connect:",error);_db=null}}return _db}
export async function upsertUser(user:InsertUser):Promise<void>{if(!user.openId)throw new Error("User openId is required for upsert");const db=await getDb();if(!db)return;const values:InsertUser={openId:user.openId};const updateSet:Record<string,unknown>={};const textFields=["name","email","loginMethod"] as const;for(const field of textFields){if(user[field]!==undefined){values[field]=user[field]??null;updateSet[field]=user[field]??null}}if(user.lastSignedIn!==undefined){values.lastSignedIn=user.lastSignedIn;updateSet.lastSignedIn=user.lastSignedIn}if(user.role!==undefined){values.role=user.role;updateSet.role=user.role}else if(user.openId===ENV.ownerOpenId){values.role="admin";updateSet.role="admin"}if(!values.lastSignedIn)values.lastSignedIn=new Date();if(!Object.keys(updateSet).length)updateSet.lastSignedIn=new Date();await db.insert(users).values(values).onDuplicateKeyUpdate({set:updateSet})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return undefined;const result=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return result[0]}
export async function listCustomers(){const db=await getDb();if(!db)return [];return db.select().from(customers).orderBy(desc(customers.updatedAt))}
export async function createCustomer(input:typeof customers.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(customers).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(customers).where(eq(customers.id,id)).limit(1);return rows[0]}
export async function updateCustomer(id:number,input:Partial<typeof customers.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(customers).set(input).where(eq(customers.id,id));const rows=await db.select().from(customers).where(eq(customers.id,id)).limit(1);return rows[0]}

async function appendOrderHistory(orderId:number,action:string,details:unknown){const db=await getDb();if(!db)return;await db.insert(orderHistory).values({orderId,action,details:typeof details === "string" ? details : JSON.stringify(details)});}
export async function listOrders(){const db=await getDb();if(!db)return [];return db.select().from(orders).orderBy(desc(orders.createdAt))}
export async function getOrderDetails(id:number){const db=await getDb();if(!db)return undefined;const orderRows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);if(!orderRows[0])return undefined;const customerRows=await db.select().from(customers).where(eq(customers.id,orderRows[0].customerId)).limit(1);const history=await db.select().from(orderHistory).where(eq(orderHistory.orderId,id)).orderBy(desc(orderHistory.createdAt));return {order:orderRows[0],customer:customerRows[0],history};}
export async function listOrderHistory(orderId:number){const db=await getDb();if(!db)return [];return db.select().from(orderHistory).where(eq(orderHistory.orderId,orderId)).orderBy(desc(orderHistory.createdAt))}
export async function createOrder(input:typeof orders.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(orders).values(input);const id=Number(result[0].insertId);await appendOrderHistory(id,"created",{total:input.total,status:input.status ?? "pending",jalaliDate:input.jalaliDate,itemsJson:input.itemsJson});const rows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);return rows[0]}
export async function updateOrder(id:number,input:Partial<typeof orders.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(orders).set(input).where(eq(orders.id,id));await appendOrderHistory(id,input.status === "delivered" ? "delivered" : "updated",input);const rows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);return rows[0]}
export async function listActivities(){const db=await getDb();if(!db)return [];return db.select().from(activities).orderBy(desc(activities.createdAt)).limit(40)}
export async function createActivity(text:string){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(activities).values({text});const id=Number(result[0].insertId);const rows=await db.select().from(activities).where(eq(activities.id,id)).limit(1);return rows[0]}

export async function listInventoryItems(){const db=await getDb();if(!db)return [];return db.select().from(inventoryItems).orderBy(desc(inventoryItems.updatedAt))}
export async function createInventoryItem(input:typeof inventoryItems.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(inventoryItems).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(inventoryItems).where(eq(inventoryItems.id,id)).limit(1);return rows[0]}
export async function updateInventoryItem(id:number,input:Partial<typeof inventoryItems.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(inventoryItems).set(input).where(eq(inventoryItems.id,id));const rows=await db.select().from(inventoryItems).where(eq(inventoryItems.id,id)).limit(1);return rows[0]}
export async function listInventoryMovements(inventoryItemId:number){const db=await getDb();if(!db)return [];return db.select().from(inventoryMovements).where(eq(inventoryMovements.inventoryItemId,inventoryItemId)).orderBy(desc(inventoryMovements.createdAt))}
export async function createInventoryMovement(input:typeof inventoryMovements.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(inventoryMovements).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(inventoryMovements).where(eq(inventoryMovements.id,id)).limit(1);return rows[0]}
export async function listUsers(){const db=await getDb();if(!db)return [];return db.select({id:users.id,name:users.name,email:users.email,role:users.role,permissionsJson:users.permissionsJson,createdAt:users.createdAt,updatedAt:users.updatedAt}).from(users).orderBy(desc(users.updatedAt))}
export async function updateUser(id:number,input:Partial<typeof users.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(users).set(input).where(eq(users.id,id));const rows=await db.select({id:users.id,name:users.name,email:users.email,role:users.role,permissionsJson:users.permissionsJson,createdAt:users.createdAt,updatedAt:users.updatedAt}).from(users).where(eq(users.id,id)).limit(1);return rows[0]}
