import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { randomBytes, scrypt as scryptCallback, timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import { activities, activityDismissals, appSettings, customers, InsertUser, inventoryItems, inventoryMovements, orderHistory, orders, restoreHistory, settingsHistory, users } from "../drizzle/schema";
import { ENV } from './_core/env';

let _db: ReturnType<typeof drizzle> | null = null;
const scrypt=promisify(scryptCallback);
export async function hashPassword(password:string){const salt=randomBytes(16);const derived=await scrypt(password,salt,64) as Buffer;return `scrypt$${salt.toString("hex")}$${derived.toString("hex")}`;}
export async function verifyPassword(password:string,encoded:string){try{const [scheme,saltHex,hashHex]=encoded.split("$");if(scheme!=="scrypt"||!saltHex||!hashHex)return false;const derived=await scrypt(password,Buffer.from(saltHex,"hex"),64) as Buffer;const expected=Buffer.from(hashHex,"hex");return expected.length===derived.length&&timingSafeEqual(expected,derived);}catch{return false;}}
export async function getDb(){if(!_db&&process.env.DATABASE_URL){try{_db=drizzle(process.env.DATABASE_URL)}catch(error){console.warn("[Database] Failed to connect:",error);_db=null}}return _db}
export async function upsertUser(user:InsertUser):Promise<void>{if(!user.openId)throw new Error("User openId is required for upsert");const db=await getDb();if(!db)return;const values:InsertUser={openId:user.openId};const updateSet:Record<string,unknown>={};const textFields=["name","email","loginMethod"] as const;for(const field of textFields){if(user[field]!==undefined){values[field]=user[field]??null;updateSet[field]=user[field]??null}}if(user.lastSignedIn!==undefined){values.lastSignedIn=user.lastSignedIn;updateSet.lastSignedIn=user.lastSignedIn}if(user.role!==undefined){values.role=user.role;updateSet.role=user.role}else if(user.openId===ENV.ownerOpenId){values.role="admin";updateSet.role="admin"}if(!values.lastSignedIn)values.lastSignedIn=new Date();if(!Object.keys(updateSet).length)updateSet.lastSignedIn=new Date();await db.insert(users).values(values).onDuplicateKeyUpdate({set:updateSet})}
export async function getUserByOpenId(openId:string){const db=await getDb();if(!db)return undefined;const result=await db.select().from(users).where(eq(users.openId,openId)).limit(1);return result[0]}
export async function listCustomers(){const db=await getDb();if(!db)return [];return db.select().from(customers).orderBy(desc(customers.updatedAt))}
export async function createCustomer(input:typeof customers.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(customers).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(customers).where(eq(customers.id,id)).limit(1);return rows[0]}
export async function updateCustomer(id:number,input:Partial<typeof customers.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(customers).set(input).where(eq(customers.id,id));const rows=await db.select().from(customers).where(eq(customers.id,id)).limit(1);return rows[0]}

async function appendOrderHistory(orderId:number,action:string,details:unknown){const db=await getDb();if(!db)return;await db.insert(orderHistory).values({orderId,action,details:typeof details === "string" ? details : JSON.stringify(details)});}
export async function listOrders(){const db=await getDb();if(!db)return [];return db.select().from(orders).orderBy(desc(orders.createdAt))}
export async function getOrderDetails(id:number){const db=await getDb();if(!db)return undefined;const orderRows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);if(!orderRows[0])return undefined;const customerRows=await db.select().from(customers).where(eq(customers.id,orderRows[0].customerId)).limit(1);const history=await db.select().from(orderHistory).where(eq(orderHistory.orderId,id)).orderBy(desc(orderHistory.createdAt));return {order:orderRows[0],customer:customerRows[0],history};}
export async function listOrderHistory(orderId:number){const db=await getDb();if(!db)return [];return db.select().from(orderHistory).where(eq(orderHistory.orderId,orderId)).orderBy(desc(orderHistory.createdAt))}
export async function createOrder(input:typeof orders.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(orders).values(input);const id=Number(result[0].insertId);await appendOrderHistory(id,"created",{total:input.total,status:input.status ?? "pending",jalaliDate:input.jalaliDate,itemsJson:input.itemsJson});const rows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);return rows[0]}
export async function updateOrder(id:number,input:Partial<typeof orders.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(orders).set(input).where(eq(orders.id,id));await appendOrderHistory(id,input.status === "delivered" ? "delivered" : "updated",input);const rows=await db.select().from(orders).where(eq(orders.id,id)).limit(1);return rows[0]}
export async function listActivities(userOpenId?:string){const db=await getDb();if(!db)return [];const rows=await db.select().from(activities).orderBy(desc(activities.createdAt)).limit(200);if(!userOpenId)return rows;const hidden=await db.select({activityId:activityDismissals.activityId}).from(activityDismissals).where(eq(activityDismissals.userOpenId,userOpenId));const hiddenIds=new Set(hidden.map(item=>item.activityId));return rows.filter(item=>!hiddenIds.has(item.id));}
export async function dismissActivity(activityId:number,userOpenId:string){const db=await getDb();if(!db)throw new Error("Database is not available");await db.insert(activityDismissals).values({activityId,userOpenId});return {success:true};}
export async function dismissAllActivities(userOpenId:string){const db=await getDb();if(!db)throw new Error("Database is not available");const rows=await db.select({id:activities.id}).from(activities);if(rows.length)await db.insert(activityDismissals).values(rows.map(row=>({activityId:row.id,userOpenId})));return {success:true,count:rows.length};}
export async function createActivity(text:string){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(activities).values({text});const id=Number(result[0].insertId);const rows=await db.select().from(activities).where(eq(activities.id,id)).limit(1);return rows[0]}
export async function getAppSettings(){const db=await getDb();if(!db)return [];return db.select().from(appSettings)}
export async function setAppSettings(values:Record<string,string>,actor:{openId:string;name:string}){const db=await getDb();if(!db)throw new Error("Database is not available");const current=await getAppSettings();const previous=new Map(current.map(item=>[item.key,item.value]));for(const [key,value] of Object.entries(values)){if(previous.get(key)!==value)await db.insert(settingsHistory).values({settingKey:key,previousValue:previous.get(key)||null,newValue:value,userOpenId:actor.openId,userName:actor.name});await db.insert(appSettings).values({key,value}).onDuplicateKeyUpdate({set:{value}});}return getAppSettings()}
export async function listSettingsHistory(){const db=await getDb();if(!db)return [];return db.select().from(settingsHistory).orderBy(desc(settingsHistory.createdAt)).limit(200)}

export async function listInventoryItems(){const db=await getDb();if(!db)return [];return db.select().from(inventoryItems).orderBy(desc(inventoryItems.updatedAt))}
export async function createInventoryItem(input:typeof inventoryItems.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(inventoryItems).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(inventoryItems).where(eq(inventoryItems.id,id)).limit(1);return rows[0]}
export async function updateInventoryItem(id:number,input:Partial<typeof inventoryItems.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(inventoryItems).set(input).where(eq(inventoryItems.id,id));const rows=await db.select().from(inventoryItems).where(eq(inventoryItems.id,id)).limit(1);return rows[0]}
export async function listInventoryMovements(inventoryItemId:number){const db=await getDb();if(!db)return [];return db.select().from(inventoryMovements).where(eq(inventoryMovements.inventoryItemId,inventoryItemId)).orderBy(desc(inventoryMovements.createdAt))}
export async function createInventoryMovement(input:typeof inventoryMovements.$inferInsert){const db=await getDb();if(!db)throw new Error("Database is not available");const result=await db.insert(inventoryMovements).values(input);const id=Number(result[0].insertId);const rows=await db.select().from(inventoryMovements).where(eq(inventoryMovements.id,id)).limit(1);return rows[0]}
export async function updateInventoryMovement(id:number,input:Partial<typeof inventoryMovements.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(inventoryMovements).set(input).where(eq(inventoryMovements.id,id));const rows=await db.select().from(inventoryMovements).where(eq(inventoryMovements.id,id)).limit(1);return rows[0]}
export async function softDeleteInventoryMovement(id:number,changeReason:string){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(inventoryMovements).set({isDeleted:1,changeReason}).where(eq(inventoryMovements.id,id));const rows=await db.select().from(inventoryMovements).where(eq(inventoryMovements.id,id)).limit(1);return rows[0]}
export async function listUsers(){const db=await getDb();if(!db)return [];return db.select({id:users.id,name:users.name,email:users.email,username:users.username,jobTitle:users.jobTitle,loginMethod:users.loginMethod,role:users.role,permissionsJson:users.permissionsJson,createdAt:users.createdAt,updatedAt:users.updatedAt}).from(users).orderBy(desc(users.updatedAt))}
export async function getUserByUsername(username:string){const db=await getDb();if(!db)return undefined;const rows=await db.select().from(users).where(eq(users.username,username)).limit(1);return rows[0]}
export async function createEmployee(input:{name:string;jobTitle:string;username:string;password:string}){const db=await getDb();if(!db)throw new Error("Database is not available");const username=input.username.trim().toLowerCase();if(await getUserByUsername(username))throw new Error("نام کاربری قبلاً استفاده شده است");const result=await db.insert(users).values({openId:`local_${randomBytes(18).toString("hex")}`,name:input.name.trim(),jobTitle:input.jobTitle.trim(),username,passwordHash:await hashPassword(input.password),loginMethod:"local",role:"user",permissionsJson:JSON.stringify({})});const id=Number(result[0].insertId);return db.select({id:users.id,name:users.name,username:users.username,jobTitle:users.jobTitle,role:users.role,permissionsJson:users.permissionsJson}).from(users).where(eq(users.id,id)).limit(1).then(rows=>rows[0]);}
export async function authenticateEmployee(username:string,password:string){const user=await getUserByUsername(username.trim().toLowerCase());if(!user?.passwordHash||!(await verifyPassword(password,user.passwordHash)))return undefined;const db=await getDb();if(db)await db.update(users).set({lastSignedIn:new Date()}).where(eq(users.id,user.id));return user;}
export async function updateUser(id:number,input:Partial<typeof users.$inferInsert>){const db=await getDb();if(!db)throw new Error("Database is not available");await db.update(users).set(input).where(eq(users.id,id));const rows=await db.select({id:users.id,name:users.name,email:users.email,username:users.username,jobTitle:users.jobTitle,loginMethod:users.loginMethod,role:users.role,permissionsJson:users.permissionsJson,createdAt:users.createdAt,updatedAt:users.updatedAt}).from(users).where(eq(users.id,id)).limit(1);return rows[0]}
export async function exportDatabase(){const db=await getDb();if(!db)throw new Error("Database is not available");const [userRows,customerRows,orderRows,historyRows,activityRows,inventoryRows,movementRows]=await Promise.all([db.select().from(users),db.select().from(customers),db.select().from(orders),db.select().from(orderHistory),db.select().from(activities),db.select().from(inventoryItems),db.select().from(inventoryMovements)]);return {version:1,exportedAt:new Date().toISOString(),tables:{users:userRows,customers:customerRows,orders:orderRows,orderHistory:historyRows,activities:activityRows,inventoryItems:inventoryRows,inventoryMovements:movementRows}}}
export async function listRestoreHistory(){const db=await getDb();if(!db)return [];return db.select().from(restoreHistory).orderBy(desc(restoreHistory.createdAt)).limit(50)}
export async function restoreDatabase(payload:unknown,actor:{userOpenId?:string|null;userName:string}){const db=await getDb();if(!db)throw new Error("Database is not available");if(!payload||typeof payload!=="object"||!("tables" in payload))throw new Error("Invalid backup file");const typedPayload=payload as {version?:number;tables?:Record<string,unknown>};const tables=typedPayload.tables;if(!tables||!Array.isArray(tables.users)||!Array.isArray(tables.customers)||!Array.isArray(tables.orders)||!Array.isArray(tables.orderHistory)||!Array.isArray(tables.activities)||!Array.isArray(tables.inventoryItems)||!Array.isArray(tables.inventoryMovements))throw new Error("Backup file is incomplete");const usersData=tables.users as any[],customersData=tables.customers as any[],ordersData=tables.orders as any[],historyData=tables.orderHistory as any[],activitiesData=tables.activities as any[],inventoryData=tables.inventoryItems as any[],movementsData=tables.inventoryMovements as any[];const recordCount=Object.values(tables).reduce<number>((sum,rows)=>sum+(Array.isArray(rows)?rows.length:0),0);await db.transaction(async tx=>{await tx.delete(orderHistory);await tx.delete(inventoryMovements);await tx.delete(orders);await tx.delete(customers);await tx.delete(activities);await tx.delete(inventoryItems);await tx.delete(users);if(usersData.length)await tx.insert(users).values(usersData);if(customersData.length)await tx.insert(customers).values(customersData);if(ordersData.length)await tx.insert(orders).values(ordersData);if(historyData.length)await tx.insert(orderHistory).values(historyData);if(activitiesData.length)await tx.insert(activities).values(activitiesData);if(inventoryData.length)await tx.insert(inventoryItems).values(inventoryData);if(movementsData.length)await tx.insert(inventoryMovements).values(movementsData);await tx.insert(restoreHistory).values({userOpenId:actor.userOpenId??null,userName:actor.userName,backupVersion:typedPayload.version??1,recordCount})});return {success:true,recordCount}}
