from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/Sales.tsx')
s=p.read_text()
needle='const statusClass=(s:CustomerStatus)=>s==="ثابت"?"green":s==="غیر ثابت"?"gray":s==="نیاز به پیگیری"?"red":"amber";'
insert=needle+'\nconst printInvoice=(order:Order,customerName:string)=>{let items:any[]=[];try{items=JSON.parse(order.itemsJson)}catch{}const rows=items.map(item=>`<tr><td>${item.product||"محصول"}</td><td>${item.fabric||"—"} · ${item.color||"—"}</td><td>${item.qty||0}</td><td>${(item.sizes||[]).filter((row:any)=>row.qty>0).map((row:any)=>`${row.size}: ${row.qty}`).join("، ")||"—"}</td><td>${(item.front||"بدون چاپ")} / ${(item.back||"بدون چاپ")}</td><td>${money((item.qty||0)*((item.unit||0)+(item.frontPrice||0)+(item.backPrice||0)+(item.materialPrice||0)))} تومان</td></tr>`).join("");const popup=window.open("","_blank","width=980,height=760");if(!popup)return;popup.document.write(`<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>پیش‌فاکتور سفارش #${order.id}</title><style>body{font-family:Tahoma,Arial,sans-serif;padding:32px;color:#17233d}h1{font-size:24px}p{color:#526079}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{border:1px solid #dce2eb;padding:10px;text-align:right;font-size:13px}th{background:#f1f4f8}.total{margin-top:22px;font-size:20px;font-weight:700}</style></head><body><h1>پیش‌فاکتور تولیدی پوشاک سپید</h1><p>مشتری: ${customerName} · سفارش #${order.id} · تاریخ: ${order.jalaliDate}</p><table><thead><tr><th>محصول</th><th>جنس / رنگ</th><th>تعداد</th><th>سایزها</th><th>چاپ جلو / پشت</th><th>مبلغ</th></tr></thead><tbody>${rows}</tbody></table><div class="total">مبلغ نهایی: ${money(order.total)} تومان</div><script>window.onload=()=>{window.print()}</script></body></html>`);popup.document.close();};'
if needle not in s: raise SystemExit('status marker not found')
s=s.replace(needle,insert,1)
s=s.replace('<div className="edit-order-head"><div><strong>خرید {(i+1).toLocaleString("fa-IR")} · سفارش #{order.id}</strong><span>{order.jalaliDate} · {order.status==="delivered"?"تحویل داده شده":"در انتظار تحویل"}</span></div><b>{money(order.total)}</b></div>', '<div className="edit-order-head"><div><strong>خرید {(i+1).toLocaleString("fa-IR")} · سفارش #{order.id}</strong><span>{order.jalaliDate} · {order.status==="delivered"?"تحویل داده شده":"در انتظار تحویل"}</span></div><b>{money(order.total)}</b></div><div className="edit-order-actions"><button type="button" className="text-button" onClick={()=>setLocation(`/orders/new?customer=${selected?.id}&order=${order.id}`)}>ویرایش سفارش</button><button type="button" className="text-button" onClick={()=>printInvoice(order,selected?.name||"")}>چاپ / ذخیره PDF</button></div>')
old='<div><b>{money(order.total)}</b><small>{order.jalaliDate}</small></div></div>})}'
new='<div><b>{money(order.total)}</b><small>{order.jalaliDate}</small><div className="purchase-actions"><button className="text-button" onClick={()=>setLocation(`/orders/new?customer=${selected.id}&order=${order.id}`)}>ویرایش</button><button className="text-button" onClick={()=>printInvoice(order,selected.name)}>چاپ</button></div></div></div>})}'
if old not in s: raise SystemExit('purchase marker not found')
s=s.replace(old,new,1)
p.write_text(s)
print('order actions added')
