from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/components/Map.tsx')
s=p.read_text().replace('`/maps/api/js?key=${API_KEY}&v=weekly`','`/maps/api/js?key=${API_KEY}&v=weekly&libraries=marker`')
p.write_text(s)

p=Path('/home/ubuntu/taraz-operations/client/src/pages/OrderEntry.tsx')
s=p.read_text()
s=s.replace('const [mapModal,setMapModal]=useState(false); const [mapMarker,setMapMarker]=useState<google.maps.marker.AdvancedMarkerElement|null>(null); const [locationLabel,setLocationLabel]=useState("");', 'const [mapModal,setMapModal]=useState(false); const [mapMarker,setMapMarker]=useState<google.maps.marker.AdvancedMarkerElement|null>(null); const [mapInstance,setMapInstance]=useState<google.maps.Map|null>(null); const [locationLabel,setLocationLabel]=useState(""); const [locationStatus,setLocationStatus]=useState("");')
old='onMapReady={map=>{if(mapMarker)mapMarker.map=null;const marker=new window.google.maps.marker.AdvancedMarkerElement({map,position:{lat:point.lat,lng:point.lng},title:point.label});setMapMarker(marker);map.addListener("click",(event: google.maps.MapMouseEvent)=>{if(!event.latLng)return;const next={lat:event.latLng.lat(),lng:event.latLng.lng(),label:locationLabel.trim()||`مختصات ${event.latLng.lat().toFixed(4)}، ${event.latLng.lng().toFixed(4)}`};marker.position={lat:next.lat,lng:next.lng};setPoint(next);setLocationLabel(next.label);});}}/>'
new='onMapReady={map=>{setMapInstance(map);if(mapMarker)mapMarker.map=null;const marker=new window.google.maps.marker.AdvancedMarkerElement({map,position:{lat:point.lat,lng:point.lng},title:point.label});setMapMarker(marker);map.addListener("click",(event: google.maps.MapMouseEvent)=>{if(!event.latLng)return;const next={lat:event.latLng.lat(),lng:event.latLng.lng(),label:locationLabel.trim()||`نقطه انتخاب‌شده · ${event.latLng.lat().toFixed(4)}، ${event.latLng.lng().toFixed(4)}`};marker.position={lat:next.lat,lng:next.lng};marker.title=next.label;setPoint(next);setLocationLabel(next.label);setLocationStatus("نقطه انتخاب شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");});}}/>'
if old not in s: raise SystemExit('map block not found')
s=s.replace(old,new,1)
needle='<label className="location-address-input">آدرس، محله یا توضیح موقعیت<input value={locationLabel} onChange={e=>setLocationLabel(e.target.value)} placeholder="مثلاً تهران، ونک، خیابان ملاصدرا"/><small>می‌توانید متن را تایپ کنید یا مستقیماً روی نقشه کلیک کنید.</small></label><MapView'
replacement='<label className="location-address-input">آدرس، محله یا توضیح موقعیت<input value={locationLabel} onChange={e=>setLocationLabel(e.target.value)} placeholder="مثلاً تهران، ونک، خیابان ملاصدرا"/><small>می‌توانید متن را تایپ کنید یا مستقیماً روی نقشه کلیک کنید.</small></label><button type="button" className="current-location-button" onClick={()=>{if(!navigator.geolocation){setLocationStatus("مرورگر شما موقعیت لحظه‌ای را پشتیبانی نمی‌کند.");return;}setLocationStatus("در حال دریافت موقعیت لحظه‌ای شما...");navigator.geolocation.getCurrentPosition(position=>{const next={lat:position.coords.latitude,lng:position.coords.longitude,label:"موقعیت فعلی من"};setPoint(next);setLocationLabel(next.label);mapInstance?.setCenter(next);mapInstance?.setZoom(16);if(mapMarker){mapMarker.position=next;mapMarker.title=next.label;}setLocationStatus("موقعیت فعلی دریافت شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");},()=>setLocationStatus("دسترسی به موقعیت فعلی رد شد یا در دسترس نیست."),{enableHighAccuracy:true,timeout:10000,maximumAge:0})}}><MapPin size={15}/> ثبت موقعیت فعلی من</button>{locationStatus&&<div className="location-status">{locationStatus}</div>}<MapView'
if needle not in s: raise SystemExit('location input block not found')
s=s.replace(needle,replacement,1)
p.write_text(s)

css=Path('/home/ubuntu/taraz-operations/client/src/factory-pages.css')
css.write_text(css.read_text()+'''\n.current-location-button{display:inline-flex;align-items:center;gap:6px;width:max-content;border:1px solid #cbd5e3;background:#eef3f9;color:#142344;border-radius:8px;padding:8px 11px;font:inherit;font-size:12px;cursor:pointer;margin-bottom:10px}.current-location-button:hover{background:#dfe8f4}.location-status{margin:-4px 0 10px;color:#244b88;font-size:11px}.dark .current-location-button{background:#1b2942;border-color:#40516e;color:#fff}.dark .location-status{color:#b9cbe7}\n''')
print('live location added')
