from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('  const [deliveryOrderId, setDeliveryOrderId] = useState<string | null>(null);', '  const [deliveryOrderId, setDeliveryOrderId] = useState<string | null>(null);\n  const [deliveryMapOrderId, setDeliveryMapOrderId] = useState<string | null>(null);')
s=s.replace('  const lowStock = materials.filter(item => item.stock <= item.threshold).length;', '  const lowStock = materials.filter(item => item.stock <= item.threshold).length;\n  const monthlyDeliveryTotals = useMemo(() => { const now = new Date(); return Array.from({length:6}, (_,index) => { const month=new Date(now.getFullYear(),now.getMonth()-index,1); const total=delivered.filter(order => { const date=new Date(order.delivery?.completedAt ?? order.createdAt); return date.getFullYear()===month.getFullYear() && date.getMonth()===month.getMonth(); }).reduce((sum,order)=>sum+(order.delivery?.cost??0),0); return {label:new Intl.DateTimeFormat("fa-IR-u-ca-persian",{month:"long",year:"numeric"}).format(month),total}; }); }, [delivered]);')
s=s.replace('  const showToast = (message: string) => setToast(message);', '  const showToast = (message: string) => setToast(message);\n  const logActivity = (text: string) => { try { const current=JSON.parse(localStorage.getItem("sepid-activities")||"[]"); localStorage.setItem("sepid-activities",JSON.stringify([{id:Date.now(),text,time:Date.now()},...current].slice(0,40))); } catch {} };')
s=s.replace('      showToast("اطلاعات سفارش ویرایش شد.");', '      showToast("اطلاعات سفارش ویرایش شد."); logActivity(`سفارش ${editOrderId} ویرایش شد`);')
s=s.replace('setOrders(data => [newOrder, ...data]); setSelectedOrderId(newOrder.id); showToast("سفارش ثبت و به صف تحویل اضافه شد.");', 'setOrders(data => [newOrder, ...data]); setSelectedOrderId(newOrder.id); showToast("سفارش ثبت و به صف تحویل اضافه شد."); logActivity(`سفارش جدید ${newOrder.id} برای ${newOrder.customer} ثبت شد`);')
s=s.replace('setDeliveryOrderId(null); setDeliveryTab("delivered"); showToast("هزینه و اطلاعات ارسال ثبت شد؛ سفارش تحویل‌شده شد.");', 'setDeliveryOrderId(null); setDeliveryTab("delivered"); showToast("هزینه و اطلاعات ارسال ثبت شد؛ سفارش تحویل‌شده شد."); logActivity(`تحویل سفارش ${deliveryOrderId} ثبت شد`);')
s=s.replace('showToast("پوشاک ویرایش شد.");', 'showToast("پوشاک ویرایش شد."); logActivity(`پوشاک ${productDraft.type} ویرایش شد`);')
s=s.replace('showToast("پوشاک به انبار اضافه شد.");', 'showToast("پوشاک به انبار اضافه شد."); logActivity(`پوشاک جدید ${productDraft.type} به انبار اضافه شد`);')
s=s.replace('showToast("ماده اولیه ویرایش شد.");', 'showToast("ماده اولیه ویرایش شد."); logActivity(`ماده اولیه ${materialDraft.name} ویرایش شد`);')
s=s.replace('showToast("ماده اولیه به انبار اضافه شد.");', 'showToast("ماده اولیه به انبار اضافه شد."); logActivity(`ماده اولیه جدید ${materialDraft.name} اضافه شد`);')
s=s.replace('action={<button className="primary-button" onClick={openNewOrder}><Plus size={18} /> ثبت سفارش جدید</button>}', 'action={undefined}', 1)
old='''    <div className="delivery-tabs"><button className={deliveryTab === "pending" ? "selected" : ""} onClick={() => setDeliveryTab("pending")}><Clock3 size={17} /> در انتظار تحویل <b>{number(pending.length)}</b></button><button className={deliveryTab === "delivered" ? "selected" : ""} onClick={() => setDeliveryTab("delivered")}><PackageCheck size={17} /> تحویل داده‌شده <b>{number(delivered.length)}</b></button></div>
    <section className="toolbar delivery-toolbar">'''
new='''    <div className="delivery-summary-grid">{monthlyDeliveryTotals.slice(0,3).map((item,index)=><div className="delivery-summary-box" key={item.label}><span>{index===0?"دریافتی این ماه":item.label}</span><strong>{money(item.total)}</strong><small>{index===0?`${number(delivered.filter(order=>{const date=new Date(order.delivery?.completedAt??order.createdAt);const now=new Date();return date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()}).length)} تحویل ثبت‌شده`:"جمع هزینه ارسال"}</small></div>)}</div><div className="delivery-tabs"><button className={deliveryTab === "pending" ? "selected" : ""} onClick={() => setDeliveryTab("pending")}><Clock3 size={17} /> در انتظار تحویل <b>{number(pending.length)}</b></button><button className={deliveryTab === "delivered" ? "selected" : ""} onClick={() => setDeliveryTab("delivered")}><PackageCheck size={17} /> تحویل داده‌شده <b>{number(delivered.length)}</b></button></div>
    <section className="toolbar delivery-toolbar">'''
if old not in s: raise SystemExit('delivery tabs marker not found')
s=s.replace(old,new,1)
s=s.replace('''<div className="delivery-history"><div><Truck size={17} /><span>ارسال با <strong>{order.delivery?.method}</strong> · {jalaliDate(order.delivery?.completedAt ?? order.createdAt, true)}</span></div><div><CircleDollarSign size={17} /><span>مبلغ دریافتی بابت ارسال: <strong>{money(order.delivery?.cost ?? 0)}</strong></span></div><p>{order.delivery?.note}</p></div>}''','''<div className="delivery-history"><div><Truck size={17} /><span>ارسال با <strong>{order.delivery?.method}</strong> · {jalaliDate(order.delivery?.completedAt ?? order.createdAt, true)}</span></div><div><CircleDollarSign size={17} /><span>مبلغ دریافتی بابت ارسال: <strong>{money(order.delivery?.cost ?? 0)}</strong></span></div><p>{order.delivery?.note}</p><button type="button" className="outline-button compact delivery-location-button" onClick={()=>setDeliveryMapOrderId(order.id)}><MapPin size={15}/> مشاهده لوکیشن ثبت‌شده</button></div>}''')
marker='''    <Modal open={Boolean(deliveryOrderId)} onClose={() => setDeliveryOrderId(null)} title="ثبت تحویل محصول"'''
insert='''    <Modal open={Boolean(deliveryMapOrderId)} onClose={() => setDeliveryMapOrderId(null)} title="لوکیشن ثبت‌شده سفارش" subtitle="موقعیتی که هنگام ثبت سفارش برای این مشتری ذخیره شده است.">{(()=>{const order=orders.find(item=>item.id===deliveryMapOrderId);return order?<div className="delivery-map-modal"><MiniMap location={order.location}/><div className="selected-location-row"><MapPin size={16}/><span>{order.location.label}</span></div><p>{order.customer} · {order.address}</p></div>:null})()}</Modal>
    <Modal open={Boolean(deliveryOrderId)} onClose={() => setDeliveryOrderId(null)} title="ثبت تحویل محصول"'''
if marker not in s: raise SystemExit('delivery modal marker not found')
s=s.replace(marker,insert,1)
p.write_text(s)
print('home operations enhanced')
