from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/Sales.tsx')
s=p.read_text()
needle='</label></div><div className="modal-actions"><button type="button" className="outline-button" onClick={()=>setEditOpen(false)}>انصراف</button>'
insert='''</label></div><div className="customer-edit-history"><div className="edit-history-title"><strong>سفارش‌ها و پیش‌فاکتورهای قبلی</strong><span>{orders.filter(o=>o.customerId===selected?.id).length.toLocaleString("fa-IR")} سفارش</span></div>{orders.filter(o=>o.customerId===selected?.id).map((order,i)=>{let items:any[]=[];try{items=JSON.parse(order.itemsJson)}catch{}return <article className="edit-order-card" key={order.id}><div className="edit-order-head"><div><strong>خرید {(i+1).toLocaleString("fa-IR")} · سفارش #{order.id}</strong><span>{order.jalaliDate} · {order.status==="delivered"?"تحویل داده شده":"در انتظار تحویل"}</span></div><b>{money(order.total)}</b></div>{items.map((item,itemIndex)=><div className="edit-proforma-row" key={`${order.id}-${itemIndex}`}><div><strong>{item.product||"محصول"}</strong><span>{item.fabric||"جنس مشخص نشده"} · {item.color||"رنگ مشخص نشده"}</span></div><div><span>تعداد: {(item.qty||0).toLocaleString("fa-IR")} · سایزها: {(item.sizes||[]).filter((row:any)=>row.qty>0).map((row:any)=>`${row.size} (${row.qty})`).join("، ")||"—"}</span><span>چاپ جلو: {item.front||"بدون چاپ"} · چاپ پشت: {item.back||"بدون چاپ"}</span><span>واحد: {money(item.unit||0)} · چاپ: {money((item.frontPrice||0)+(item.backPrice||0))} · متریال: {money(item.materialPrice||0)}</span></div></div>)}{!items.length&&<p className="edit-empty-order">جزئیات اقلام این سفارش ثبت نشده است.</p>}</article>})}{!orders.some(o=>o.customerId===selected?.id)&&<div className="edit-empty-order">برای این مشتری سفارش قبلی وجود ندارد.</div>}</div><div className="modal-actions"><button type="button" className="outline-button" onClick={()=>setEditOpen(false)}>انصراف</button>'''
if needle not in s: raise SystemExit('edit modal marker not found')
s=s.replace(needle,insert,1)
p.write_text(s)
print('customer edit expanded')
