from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/OrderEntry.tsx')
s=p.read_text()
s=s.replace('const [customerPicker,setCustomerPicker]=useState(false);\n  const [orderDate', 'const [customerPicker,setCustomerPicker]=useState(false);\n  const [customerModal,setCustomerModal]=useState(false);\n  const [newCustomer,setNewCustomer]=useState<Customer>({name:"",phone:"",business:"",city:"",address:""});\n  const [customerMessage,setCustomerMessage]=useState("");\n  const [orderDate')
old='const saveCustomer=()=>{if(!customer.name.trim()||!customer.phone.trim())return;const next=[customer,...customers.filter(item=>item.phone!==customer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomerPicker(false);setSaved(false)};\n  const submitOrder=()=>{saveCustomer();setSaved(true)};'
new='const saveCustomer=()=>{if(!customer.name.trim()||!customer.phone.trim())return;const next=[customer,...customers.filter(item=>item.phone!==customer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomerPicker(false);setSaved(false)};\n  const openCustomerModal=()=>{setNewCustomer({name:"",phone:"",business:"",city:"",address:""});setCustomerMessage("");setCustomerModal(true)};\n  const saveNewCustomer=(event:React.FormEvent)=>{event.preventDefault();if(!newCustomer.name.trim()||!newCustomer.phone.trim()){setCustomerMessage("نام شخص و شماره موبایل را وارد کنید.");return;}const next=[newCustomer,...customers.filter(item=>item.phone!==newCustomer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomer(newCustomer);setCustomerModal(false);setCustomerMessage("");};\n  const submitOrder=()=>{saveCustomer();setSaved(true)};'
if old not in s: raise SystemExit('save block not found')
s=s.replace(old,new)
s=s.replace('onClick={saveCustomer}><Plus size={15}/> افزودن مشتری', 'onClick={openCustomerModal}><Plus size={15}/> افزودن مشتری')
needle='return <div className="order-entry-page"><div className="order-entry-head">'
insert='return <div className="order-entry-page">{customerModal&&<div className="customer-modal-backdrop"><form className="customer-modal" onSubmit={saveNewCustomer}><div className="customer-modal-head"><div><span className="eyebrow">دفتر مشتریان</span><h2>افزودن مشتری جدید</h2><p>این اطلاعات جدا از اقلام سفارش ذخیره می‌شود و بعداً قابل انتخاب است.</p></div><button type="button" className="modal-close" onClick={()=>setCustomerModal(false)}>×</button></div><div className="form-grid two"><label>نام شخص<input autoFocus value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})} placeholder="مثلاً مریم محمدی"/></label><label>شماره موبایل<input value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})} placeholder="۰۹۱۲ ..."/></label><label>نام شرکت / فروشگاه<input value={newCustomer.business} onChange={e=>setNewCustomer({...newCustomer,business:e.target.value})} placeholder="مثلاً کافه آتریوم"/></label><label>شهر / استان<input value={newCustomer.city} onChange={e=>setNewCustomer({...newCustomer,city:e.target.value})} placeholder="هر شهری را تایپ کنید"/></label><label className="span-two">آدرس کامل<input value={newCustomer.address} onChange={e=>setNewCustomer({...newCustomer,address:e.target.value})} placeholder="خیابان، کوچه، پلاک و ..."/></label></div>{customerMessage&&<div className="customer-form-error">{customerMessage}</div>}<div className="modal-actions"><button type="button" className="outline-button" onClick={()=>setCustomerModal(false)}>انصراف</button><button type="submit" className="primary-button"><Check size={16}/> ذخیره مشتری</button></div></form></div>}<div className="order-entry-head">'
if needle not in s: raise SystemExit('return needle not found')
s=s.replace(needle,insert,1)
p.write_text(s)

css=Path('/home/ubuntu/taraz-operations/client/src/factory-pages.css')
css.write_text(css.read_text()+'''\n.customer-modal-backdrop{position:fixed;inset:0;z-index:80;background:rgba(9,15,29,.55);display:grid;place-items:center;padding:22px}.customer-modal{width:min(650px,100%);background:#fff;border:1px solid #dce2eb;border-radius:18px;padding:24px;box-shadow:0 24px 70px rgba(10,20,40,.25)}.customer-modal-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:22px}.customer-modal-head h2{margin:5px 0;font-size:22px;color:#111b35}.customer-modal-head p{margin:0;color:#6c7886;font-size:12px}.modal-close{width:30px;height:30px;border:0;border-radius:50%;background:#eef1f5;color:#526079;font-size:22px;cursor:pointer}.customer-form-error{margin-top:12px;padding:9px 12px;border-radius:8px;background:#fff0ed;color:#a84437;font-size:12px}.dark .customer-modal{background:#111725;border-color:#33405a}.dark .customer-modal-head h2{color:#fff}.dark .customer-modal-head p{color:#a8b0c0}.dark .modal-close{background:#243047;color:#fff}\n''')
print('customer dialog fixed')
