from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/OrderEntry.tsx')
s=p.read_text()
old='onMapReady={map=>{setMapInstance(map);if(mapMarker)mapMarker.map=null;const marker=new window.google.maps.marker.AdvancedMarkerElement({map,position:{lat:point.lat,lng:point.lng},title:point.label});setMapMarker(marker);map.addListener("click",(event: google.maps.MapMouseEvent)=>{if(!event.latLng)return;const next={lat:event.latLng.lat(),lng:event.latLng.lng(),label:locationLabel.trim()||`نقطه انتخاب‌شده · ${event.latLng.lat().toFixed(4)}، ${event.latLng.lng().toFixed(4)}`};marker.position={lat:next.lat,lng:next.lng};marker.title=next.label;setPoint(next);setLocationLabel(next.label);setLocationStatus("نقطه انتخاب شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");});}}/>'
new='onMapReady={map=>{setMapInstance(map);let marker:google.maps.marker.AdvancedMarkerElement|null=null;const placeMarker=(next:{lat:number;lng:number;label:string})=>{try{if(marker)marker.map=null;marker=new window.google.maps.marker.AdvancedMarkerElement({map,position:{lat:next.lat,lng:next.lng},title:next.label});setMapMarker(marker);}catch{try{const legacy=new window.google.maps.Marker({map,position:{lat:next.lat,lng:next.lng},title:next.label});setMapMarker(legacy as unknown as google.maps.marker.AdvancedMarkerElement);}catch{}}};const commitPoint=(lat:number,lng:number)=>{const next={lat,lng,label:locationLabel.trim()||`نقطه انتخاب‌شده · ${lat.toFixed(4)}، ${lng.toFixed(4)}`};placeMarker(next);setPoint(next);setLocationLabel(next.label);setLocationStatus("نقطه انتخاب شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");};commitPoint(point.lat,point.lng);map.addListener("click",(event:google.maps.MapMouseEvent)=>{if(event.latLng)commitPoint(event.latLng.lat(),event.latLng.lng());});}}/>'
if old not in s: raise SystemExit('map handler not found')
s=s.replace(old,new,1)
old2='<button type="button" className="current-location-button" onClick={()=>{if(!navigator.geolocation){setLocationStatus("مرورگر شما موقعیت لحظه‌ای را پشتیبانی نمی‌کند.");return;}setLocationStatus("در حال دریافت موقعیت لحظه‌ای شما...");navigator.geolocation.getCurrentPosition(position=>{const next={lat:position.coords.latitude,lng:position.coords.longitude,label:"موقعیت فعلی من"};setPoint(next);setLocationLabel(next.label);mapInstance?.setCenter(next);mapInstance?.setZoom(16);if(mapMarker){mapMarker.position=next;mapMarker.title=next.label;}setLocationStatus("موقعیت فعلی دریافت شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");},()=>setLocationStatus("دسترسی به موقعیت فعلی رد شد یا در دسترس نیست."),{enableHighAccuracy:true,timeout:10000,maximumAge:0})}}><MapPin size={15}/> ثبت موقعیت فعلی من</button>'
new2='<div className="location-actions"><button type="button" className="current-location-button" onClick={()=>{if(!navigator.geolocation){setLocationStatus("مرورگر شما موقعیت لحظه‌ای را پشتیبانی نمی‌کند.");return;}setLocationStatus("در حال دریافت موقعیت لحظه‌ای شما...");navigator.geolocation.getCurrentPosition(position=>{const next={lat:position.coords.latitude,lng:position.coords.longitude,label:"موقعیت فعلی من"};setPoint(next);setLocationLabel(next.label);mapInstance?.setCenter(next);mapInstance?.setZoom(16);if(mapMarker){mapMarker.position=next;mapMarker.title=next.label;}setLocationStatus("موقعیت فعلی دریافت شد؛ برای ذخیره روی «ثبت این موقعیت» بزنید.");},()=>setLocationStatus("دسترسی به موقعیت فعلی رد شد یا در دسترس نیست."),{enableHighAccuracy:true,timeout:10000,maximumAge:0})}}><MapPin size={15}/> ثبت موقعیت فعلی من</button><button type="button" className="current-location-button" onClick={()=>{const center=mapInstance?.getCenter();if(center){const lat=center.lat(),lng=center.lng();setPoint({lat,lng,label:locationLabel.trim()||`مرکز نقشه · ${lat.toFixed(4)}، ${lng.toFixed(4)}`});setLocationStatus("مرکز نقشه انتخاب شد؛ حالا «ثبت این موقعیت» را بزنید.");}}}>انتخاب مرکز نقشه</button></div>'
if old2 not in s: raise SystemExit('live button not found')
s=s.replace(old2,new2,1)
p.write_text(s)
css=Path('/home/ubuntu/taraz-operations/client/src/factory-pages.css')
css.write_text(css.read_text()+'\n.location-actions{display:flex;flex-wrap:wrap;gap:8px}\n')
print('robust picker written')
