from pathlib import Path
p=Path('/home/ubuntu/taraz-operations/client/src/pages/OrderEntry.tsx')
s=p.read_text()
s=s.replace('import { useMemo, useState } from "react";', 'import { useEffect, useMemo, useState } from "react";')
s=s.replace('import { MapView } from "@/components/Map";', 'import { MapView } from "@/components/Map";\nimport { trpc } from "@/lib/trpc";')
s=s.replace('type Customer = { name:string; phone:string; business:string; city:string; address:string };', 'type Customer = { id?:number; name:string; phone:string; business:string; city:string; address:string; lat?:number|null; lng?:number|null };')
s=s.replace('const [customers,setCustomers]=useState<Customer[]>(()=>{try{return JSON.parse(localStorage.getItem("sepid-customers")||"[]")}catch{return []}});', 'const [customers,setCustomers]=useState<Customer[]>(()=>{try{return JSON.parse(localStorage.getItem("sepid-customers")||"[]")}catch{return []}});\n  const customersQuery=trpc.crm.customers.useQuery();\n  const createCustomerMutation=trpc.crm.createCustomer.useMutation();\n  const updateCustomerMutation=trpc.crm.updateCustomer.useMutation();\n  const createOrderMutation=trpc.crm.createOrder.useMutation();\n  const utils=trpc.useUtils();\n  useEffect(()=>{if(customersQuery.data&&customersQuery.data.length){setCustomers(customersQuery.data as Customer[]);}},[customersQuery.data]);')
old='const saveCustomer=()=>{if(!customer.name.trim()||!customer.phone.trim())return;const next=[customer,...customers.filter(item=>item.phone!==customer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomerPicker(false);setSaved(false)};'
new='const saveCustomer=async()=>{if(!customer.name.trim()||!customer.phone.trim())return null;const payload={name:customer.name.trim(),phone:customer.phone.trim(),business:customer.business.trim(),city:customer.city.trim(),address:customer.address.trim(),lat:customer.lat??point.lat,lng:customer.lng??point.lng};const savedCustomer=customer.id?await updateCustomerMutation.mutateAsync({id:customer.id,data:payload}):await createCustomerMutation.mutateAsync(payload);const nextCustomer={...customer,...savedCustomer};setCustomer(nextCustomer);const next=customers.some(item=>item.id===savedCustomer.id)?customers.map(item=>item.id===savedCustomer.id?nextCustomer:item):[nextCustomer,...customers.filter(item=>item.phone!==nextCustomer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomerPicker(false);setSaved(false);await utils.crm.customers.invalidate();return nextCustomer;};'
if old not in s: raise SystemExit('saveCustomer old not found')
s=s.replace(old,new,1)
old='const confirmLocation=()=>{const address=(locationLabel.trim()||point.label).trim();if(!address)return;const nextCustomer={...customer,address};setCustomer(nextCustomer);const nextCustomers=customers.map(item=>item.phone===customer.phone?{...item,address}:item);setCustomers(nextCustomers);localStorage.setItem("sepid-customers",JSON.stringify(nextCustomers));setPoint({...point,label:address});setLocationLabel(address);setLocationStatus("آدرس این مشتری ثبت و به‌روزرسانی شد.");setMapModal(false);};'
new='const confirmLocation=async()=>{const address=(locationLabel.trim()||point.label).trim();if(!address)return;try{const payload={name:customer.name.trim(),phone:customer.phone.trim(),business:customer.business.trim(),city:customer.city.trim(),address,lat:point.lat,lng:point.lng};const savedCustomer=customer.id?await updateCustomerMutation.mutateAsync({id:customer.id,data:{address,lat:point.lat,lng:point.lng}}):await createCustomerMutation.mutateAsync(payload);const nextCustomer={...customer,...savedCustomer,address,lat:point.lat,lng:point.lng};setCustomer(nextCustomer);const nextCustomers=customers.some(item=>item.id===savedCustomer.id)?customers.map(item=>item.id===savedCustomer.id?nextCustomer:item):[nextCustomer,...customers.filter(item=>item.phone!==nextCustomer.phone)];setCustomers(nextCustomers);localStorage.setItem("sepid-customers",JSON.stringify(nextCustomers));setPoint({...point,label:address});setLocationLabel(address);setLocationStatus("آدرس این مشتری ثبت و به‌روزرسانی شد.");setMapModal(false);await utils.crm.customers.invalidate();}catch{setLocationStatus("ذخیره آدرس انجام نشد؛ دوباره تلاش کنید.");}};'
if old not in s: raise SystemExit('confirm old not found')
s=s.replace(old,new,1)
old='const saveNewCustomer=(event:React.FormEvent)=>{event.preventDefault();if(!newCustomer.name.trim()||!newCustomer.phone.trim()){setCustomerMessage("نام شخص و شماره موبایل را وارد کنید.");return;}const next=[newCustomer,...customers.filter(item=>item.phone!==newCustomer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomer(newCustomer);setCustomerModal(false);setCustomerMessage("");};'
new='const saveNewCustomer=async(event:React.FormEvent)=>{event.preventDefault();if(!newCustomer.name.trim()||!newCustomer.phone.trim()){setCustomerMessage("نام شخص و شماره موبایل را وارد کنید.");return;}try{const savedCustomer=await createCustomerMutation.mutateAsync({...newCustomer,address:newCustomer.address.trim(),lat:null,lng:null});const nextCustomer={...newCustomer,...savedCustomer};const next=[nextCustomer,...customers.filter(item=>item.phone!==newCustomer.phone)];setCustomers(next);localStorage.setItem("sepid-customers",JSON.stringify(next));setCustomer(nextCustomer);setCustomerModal(false);setCustomerMessage("");await utils.crm.customers.invalidate();}catch{setCustomerMessage("ذخیره مشتری انجام نشد؛ دوباره تلاش کنید.");}};'
if old not in s: raise SystemExit('saveNew old not found')
s=s.replace(old,new,1)
old='const submitOrder=()=>{saveCustomer();setSaved(true)};'
new='const submitOrder=async()=>{try{const savedCustomer=await saveCustomer();if(!savedCustomer?.id)return;await createOrderMutation.mutateAsync({customerId:savedCustomer.id,jalaliDate:`${orderDate.day} ${orderDate.month} ${orderDate.year}`,address:savedCustomer.address,lat:point.lat,lng:point.lng,itemsJson:JSON.stringify(lines),total,status:"pending"});setSaved(true);}catch{setSaved(false);}};'
if old not in s: raise SystemExit('submit old not found')
s=s.replace(old,new,1)
# Selected customer should also move the map point and address immediately.
s=s.replace('onClick={()=>{setCustomer(item);setCustomerPicker(false)}}>', 'onClick={()=>{setCustomer(item);setPoint({lat:item.lat??point.lat,lng:item.lng??point.lng,label:item.address||point.label});setCustomerPicker(false)}}>', 1)
p.write_text(s)
print('persistent order form wired')
