import { Archive, Bell, Boxes, ClipboardList, LayoutDashboard, Menu, Moon, PackageCheck, Settings, ShieldCheck, ShoppingBag, Sun, Truck, UsersRound, X } from "lucide-react";
import { ReactNode, useEffect, useState } from "react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";

type Activity={id:number;text:string;createdAt:string|Date;time?:number};
export default function DashboardLayout({children}:{children:ReactNode}){
  const [location,setLocation]=useLocation();const [compact,setCompact]=useState(false);const [mobileOpen,setMobileOpen]=useState(false);const [dark,setDark]=useState(()=>localStorage.getItem("sepid-theme")==="dark");const [appSettings,setAppSettings]=useState(()=>{try{return {...{factoryName:"تولیدی پوشاک سپید",refreshInterval:"3"},...JSON.parse(localStorage.getItem("sepid-settings")||"{}")} }catch{return {factoryName:"تولیدی پوشاک سپید",refreshInterval:"3"}}});const refreshMs=Math.max(3000,Number(appSettings.refreshInterval||3)*1000);
  const [notifications,setNotifications]=useState<Activity[]>([]);const activityQuery=trpc.activities.list.useQuery(undefined,{refetchInterval:refreshMs,refetchIntervalInBackground:true});const [noticeOpen,setNoticeOpen]=useState(false);const [unreadCount,setUnreadCount]=useState(0);
  useEffect(()=>{if(!activityQuery.data)return;const next=(activityQuery.data as any[]).map(item=>({...item,time:new Date(item.createdAt).getTime()}));setNotifications(next);const seen=Number(localStorage.getItem("sepid-last-seen-activity")||"0");setUnreadCount(next.filter(item=>item.id>seen).length);try{localStorage.setItem("sepid-activities",JSON.stringify(next))}catch{}},[activityQuery.data]);
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("sepid-theme",dark?"dark":"light")},[dark]);
  useEffect(()=>{const onSettings=(event:Event)=>{const next=(event as CustomEvent).detail||{};setAppSettings((current:{factoryName:string;refreshInterval:string})=>({...current,...next}));if(next.theme)setDark(next.theme==="dark")};window.addEventListener("sepid-settings-updated",onSettings);return()=>window.removeEventListener("sepid-settings-updated",onSettings)},[]);
  const openNotifications=()=>{setNoticeOpen(value=>!value);if(!noticeOpen){const latest=notifications[0]?.id||0;localStorage.setItem("sepid-last-seen-activity",String(latest));setUnreadCount(0)}};
  const navigate=(path:string)=>{setLocation(path);setMobileOpen(false)};
  const menuItems=[{icon:LayoutDashboard,label:"نمای کلی",path:"/",exact:true},{icon:ShoppingBag,label:"فروش و مشتری‌ها",path:"/sales"},{icon:ClipboardList,label:"ثبت سفارش",path:"/orders/new"},{icon:Truck,label:"تحویل محصول",path:"/delivery"},{icon:Boxes,label:"انبار",path:"/inventory"},{icon:ShieldCheck,label:"دسترسی کاربران",path:"/access"}];
  return <div dir="rtl" className={`app-shell ${compact?"sidebar-compact":""} ${mobileOpen?"mobile-nav-open":""}`}><header className="topbar"><div className="topbar-actions"><button className="notification-button" onClick={openNotifications} aria-label="اعلان‌ها"><Bell size={19}/>{unreadCount>0&&<b>{Math.min(unreadCount,99).toLocaleString("fa-IR")}</b>}</button>{noticeOpen&&<div className="notification-popover"><div className="notification-head"><strong>اعلان‌های فعالیت</strong><span>به‌روزرسانی خودکار</span></div>{notifications.length?notifications.slice(0,12).map(item=><div className="notification-item" key={item.id}><div className="notification-dot"/><div><strong>{item.text}</strong><span>{new Intl.DateTimeFormat("fa-IR-u-ca-persian",{hour:"2-digit",minute:"2-digit",day:"numeric",month:"short"}).format(new Date(item.createdAt))}</span></div></div>):<div className="notification-empty">هنوز فعالیتی ثبت نشده است.</div>}</div>}</div></header><button className="mobile-menu-button" onClick={()=>setMobileOpen(value=>!value)} aria-label="باز کردن داشبورد">{mobileOpen?<X size={22}/>:<Menu size={22}/>}</button>{mobileOpen&&<button className="mobile-nav-backdrop" onClick={()=>setMobileOpen(false)} aria-label="بستن منو"/>}<aside className={`app-sidebar ${mobileOpen?"mobile-open":""}`}><div className="brand-row"><div className="brand-mark"><Archive size={20}/></div>{!compact&&<div><strong>{appSettings.factoryName}</strong><span>سیستم مدیریت کارخانه</span></div>}<button className="sidebar-toggle" onClick={()=>setCompact(!compact)} aria-label="جمع کردن داشبورد">‹</button></div><div className="sidebar-label">بخش‌های سیستم</div><nav className="nav-list">{menuItems.map(item=>{const active=item.exact?location===item.path:location.startsWith(item.path);return <button key={item.path} className={`nav-item ${active?"active":""}`} onClick={()=>navigate(item.path)}><item.icon size={18}/>{!compact&&<span>{item.label}</span>}{!compact&&active&&<i/>}</button>})}</nav>{!compact&&<div className="sidebar-help"><div className="help-icon"><UsersRound size={18}/></div><div><strong>کنترل سازمانی</strong><p>دسترسی کاربران و نقش‌ها را مدیریت کنید.</p></div></div>}<div className="sidebar-footer"><button className="nav-item muted" onClick={()=>setDark(value=>!value)}>{dark?<Sun size={18}/>:<Moon size={18}/>} {!compact&&<span>{dark?"حالت روشن":"حالت شب"}</span>}</button><button className={`nav-item muted ${location==="/settings"?"active":""}`} onClick={()=>navigate("/settings")}><Settings size={18}/>{!compact&&<span>تنظیمات</span>}</button><div className="account-row"><div className="avatar">ر</div>{!compact&&<div><strong>رئیس کل کارخانه</strong><span>دسترسی کامل</span></div>}<PackageCheck size={15} className="verified"/></div></div></aside><main className="app-main"><div key={location} className="page-transition">{children}</div></main></div>
}
